// СГЕНЕРИРОВАНО tools/assets/prepare_pets.py — не редактировать руками.
// Пути в require() обязаны быть литералами, поэтому конфиг генерируется.
import type { ImageSourcePropType } from 'react-native';

export type GeneratedAnimation = {
  frames: ImageSourcePropType[];
  width: number;
  height: number;
  /** Доля от самой высокой позы вида. */
  heightRatio: number;
};

export const GENERATED_ANIMATIONS: Record<
  string,
  Record<string, GeneratedAnimation>
> = {
  cat: {
    sleep: {
      frames: [
        require('../../../../assets/pets/cat-sleep-0.webp'),
        require('../../../../assets/pets/cat-sleep-1.webp'),
        require('../../../../assets/pets/cat-sleep-2.webp'),
        require('../../../../assets/pets/cat-sleep-3.webp'),
      ],
      width: 161,
      height: 141,
      heightRatio: 0.6409,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/cat-ball-0.webp'),
        require('../../../../assets/pets/cat-ball-1.webp'),
        require('../../../../assets/pets/cat-ball-2.webp'),
        require('../../../../assets/pets/cat-ball-3.webp'),
      ],
      width: 159,
      height: 223,
      heightRatio: 1.0136,
    },
    house: {
      frames: [
        require('../../../../assets/pets/cat-house-0.webp'),
        require('../../../../assets/pets/cat-house-1.webp'),
        require('../../../../assets/pets/cat-house-2.webp'),
        require('../../../../assets/pets/cat-house-3.webp'),
      ],
      width: 204,
      height: 171,
      heightRatio: 0.7773,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/cat-eat-0.webp'),
        require('../../../../assets/pets/cat-eat-1.webp'),
        require('../../../../assets/pets/cat-eat-2.webp'),
        require('../../../../assets/pets/cat-eat-3.webp'),
      ],
      width: 224,
      height: 190,
      heightRatio: 0.8636,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/cat-happy-0.webp'),
        require('../../../../assets/pets/cat-happy-1.webp'),
        require('../../../../assets/pets/cat-happy-2.webp'),
        require('../../../../assets/pets/cat-happy-3.webp'),
      ],
      width: 221,
      height: 206,
      heightRatio: 0.9364,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/cat-walk-0.webp'),
        require('../../../../assets/pets/cat-walk-1.webp'),
        require('../../../../assets/pets/cat-walk-2.webp'),
        require('../../../../assets/pets/cat-walk-3.webp'),
      ],
      width: 218,
      height: 199,
      heightRatio: 0.9045,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/cat-idle-0.webp'),
        require('../../../../assets/pets/cat-idle-1.webp'),
        require('../../../../assets/pets/cat-idle-2.webp'),
        require('../../../../assets/pets/cat-idle-3.webp'),
      ],
      width: 202,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/cat-dirty-0.webp'),
        require('../../../../assets/pets/cat-dirty-1.webp'),
        require('../../../../assets/pets/cat-dirty-2.webp'),
        require('../../../../assets/pets/cat-dirty-3.webp'),
      ],
      width: 218,
      height: 199,
      heightRatio: 0.9045,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/cat-bath-0.webp'),
        require('../../../../assets/pets/cat-bath-1.webp'),
        require('../../../../assets/pets/cat-bath-2.webp'),
        require('../../../../assets/pets/cat-bath-3.webp'),
        require('../../../../assets/pets/cat-bath-4.webp'),
        require('../../../../assets/pets/cat-bath-5.png'),
      ],
      width: 140,
      height: 142,
      heightRatio: 0.6455,
    },
  },
  dog: {
    sleep: {
      frames: [
        require('../../../../assets/pets/dog-sleep-0.webp'),
        require('../../../../assets/pets/dog-sleep-1.webp'),
        require('../../../../assets/pets/dog-sleep-2.webp'),
        require('../../../../assets/pets/dog-sleep-3.webp'),
      ],
      width: 178,
      height: 130,
      heightRatio: 0.5909,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/dog-ball-0.webp'),
        require('../../../../assets/pets/dog-ball-1.webp'),
        require('../../../../assets/pets/dog-ball-2.webp'),
        require('../../../../assets/pets/dog-ball-3.webp'),
      ],
      width: 172,
      height: 230,
      heightRatio: 1.0455,
    },
    house: {
      frames: [
        require('../../../../assets/pets/dog-house-0.webp'),
        require('../../../../assets/pets/dog-house-1.webp'),
        require('../../../../assets/pets/dog-house-2.webp'),
        require('../../../../assets/pets/dog-house-3.webp'),
      ],
      width: 213,
      height: 169,
      heightRatio: 0.7682,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/dog-happy-0.webp'),
        require('../../../../assets/pets/dog-happy-1.webp'),
        require('../../../../assets/pets/dog-happy-2.webp'),
        require('../../../../assets/pets/dog-happy-3.webp'),
      ],
      width: 225,
      height: 214,
      heightRatio: 0.9727,
    },
    play: {
      frames: [
        require('../../../../assets/pets/dog-play-0.webp'),
        require('../../../../assets/pets/dog-play-1.webp'),
        require('../../../../assets/pets/dog-play-2.webp'),
        require('../../../../assets/pets/dog-play-3.webp'),
      ],
      width: 249,
      height: 162,
      heightRatio: 0.7364,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/dog-eat-0.webp'),
        require('../../../../assets/pets/dog-eat-1.webp'),
        require('../../../../assets/pets/dog-eat-2.webp'),
        require('../../../../assets/pets/dog-eat-3.webp'),
      ],
      width: 263,
      height: 194,
      heightRatio: 0.8818,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/dog-walk-0.webp'),
        require('../../../../assets/pets/dog-walk-1.webp'),
        require('../../../../assets/pets/dog-walk-2.webp'),
        require('../../../../assets/pets/dog-walk-3.webp'),
      ],
      width: 236,
      height: 204,
      heightRatio: 0.9273,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/dog-idle-0.webp'),
        require('../../../../assets/pets/dog-idle-1.webp'),
        require('../../../../assets/pets/dog-idle-2.webp'),
        require('../../../../assets/pets/dog-idle-3.webp'),
      ],
      width: 225,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/dog-dirty-0.webp'),
        require('../../../../assets/pets/dog-dirty-1.webp'),
        require('../../../../assets/pets/dog-dirty-2.webp'),
        require('../../../../assets/pets/dog-dirty-3.webp'),
      ],
      width: 236,
      height: 204,
      heightRatio: 0.9273,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/dog-bath-0.png'),
        require('../../../../assets/pets/dog-bath-1.png'),
        require('../../../../assets/pets/dog-bath-2.webp'),
        require('../../../../assets/pets/dog-bath-3.png'),
        require('../../../../assets/pets/dog-bath-4.png'),
        require('../../../../assets/pets/dog-bath-5.png'),
      ],
      width: 143,
      height: 154,
      heightRatio: 0.7,
    },
  },
  pig: {
    sleep: {
      frames: [
        require('../../../../assets/pets/pig-sleep-0.webp'),
        require('../../../../assets/pets/pig-sleep-1.webp'),
        require('../../../../assets/pets/pig-sleep-2.webp'),
        require('../../../../assets/pets/pig-sleep-3.webp'),
      ],
      width: 185,
      height: 143,
      heightRatio: 0.65,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/pig-ball-0.webp'),
        require('../../../../assets/pets/pig-ball-1.webp'),
        require('../../../../assets/pets/pig-ball-2.webp'),
        require('../../../../assets/pets/pig-ball-3.webp'),
      ],
      width: 178,
      height: 193,
      heightRatio: 0.8773,
    },
    house: {
      frames: [
        require('../../../../assets/pets/pig-house-0.webp'),
        require('../../../../assets/pets/pig-house-1.webp'),
        require('../../../../assets/pets/pig-house-2.webp'),
        require('../../../../assets/pets/pig-house-3.webp'),
      ],
      width: 215,
      height: 171,
      heightRatio: 0.7773,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/pig-idle-0.webp'),
        require('../../../../assets/pets/pig-idle-1.webp'),
        require('../../../../assets/pets/pig-idle-2.webp'),
        require('../../../../assets/pets/pig-idle-3.webp'),
      ],
      width: 236,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/pig-dirty-0.webp'),
        require('../../../../assets/pets/pig-dirty-1.webp'),
        require('../../../../assets/pets/pig-dirty-2.webp'),
        require('../../../../assets/pets/pig-dirty-3.webp'),
      ],
      width: 225,
      height: 206,
      heightRatio: 0.9364,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/pig-bath-0.png'),
        require('../../../../assets/pets/pig-bath-1.png'),
        require('../../../../assets/pets/pig-bath-2.webp'),
        require('../../../../assets/pets/pig-bath-3.png'),
        require('../../../../assets/pets/pig-bath-4.png'),
        require('../../../../assets/pets/pig-bath-5.png'),
      ],
      width: 135,
      height: 155,
      heightRatio: 0.7045,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/pig-walk-0.webp'),
        require('../../../../assets/pets/pig-walk-1.webp'),
        require('../../../../assets/pets/pig-walk-2.webp'),
        require('../../../../assets/pets/pig-walk-3.webp'),
      ],
      width: 225,
      height: 206,
      heightRatio: 0.9364,
    },
    play: {
      frames: [
        require('../../../../assets/pets/pig-play-0.webp'),
        require('../../../../assets/pets/pig-play-1.webp'),
        require('../../../../assets/pets/pig-play-2.webp'),
        require('../../../../assets/pets/pig-play-3.webp'),
      ],
      width: 236,
      height: 224,
      heightRatio: 1.0182,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/pig-happy-0.webp'),
        require('../../../../assets/pets/pig-happy-1.webp'),
        require('../../../../assets/pets/pig-happy-2.webp'),
        require('../../../../assets/pets/pig-happy-3.webp'),
      ],
      width: 229,
      height: 232,
      heightRatio: 1.0545,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/pig-eat-0.webp'),
        require('../../../../assets/pets/pig-eat-1.webp'),
        require('../../../../assets/pets/pig-eat-2.webp'),
        require('../../../../assets/pets/pig-eat-3.webp'),
      ],
      width: 254,
      height: 197,
      heightRatio: 0.8955,
    },
  },
  monkey: {
    sleep: {
      frames: [
        require('../../../../assets/pets/monkey-sleep-0.webp'),
        require('../../../../assets/pets/monkey-sleep-1.webp'),
        require('../../../../assets/pets/monkey-sleep-2.webp'),
        require('../../../../assets/pets/monkey-sleep-3.webp'),
      ],
      width: 173,
      height: 146,
      heightRatio: 0.6636,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/monkey-ball-0.webp'),
        require('../../../../assets/pets/monkey-ball-1.webp'),
        require('../../../../assets/pets/monkey-ball-2.webp'),
        require('../../../../assets/pets/monkey-ball-3.webp'),
      ],
      width: 173,
      height: 244,
      heightRatio: 1.1091,
    },
    house: {
      frames: [
        require('../../../../assets/pets/monkey-house-0.webp'),
        require('../../../../assets/pets/monkey-house-1.webp'),
        require('../../../../assets/pets/monkey-house-2.webp'),
        require('../../../../assets/pets/monkey-house-3.webp'),
      ],
      width: 215,
      height: 170,
      heightRatio: 0.7727,
    },
    play: {
      frames: [
        require('../../../../assets/pets/monkey-play-0.webp'),
        require('../../../../assets/pets/monkey-play-1.webp'),
        require('../../../../assets/pets/monkey-play-2.webp'),
        require('../../../../assets/pets/monkey-play-3.webp'),
      ],
      width: 256,
      height: 238,
      heightRatio: 1.0818,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/monkey-happy-0.webp'),
        require('../../../../assets/pets/monkey-happy-1.webp'),
        require('../../../../assets/pets/monkey-happy-2.webp'),
        require('../../../../assets/pets/monkey-happy-3.webp'),
      ],
      width: 239,
      height: 231,
      heightRatio: 1.05,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/monkey-walk-0.webp'),
        require('../../../../assets/pets/monkey-walk-1.webp'),
        require('../../../../assets/pets/monkey-walk-2.webp'),
        require('../../../../assets/pets/monkey-walk-3.webp'),
      ],
      width: 236,
      height: 221,
      heightRatio: 1.0045,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/monkey-idle-0.webp'),
        require('../../../../assets/pets/monkey-idle-1.webp'),
        require('../../../../assets/pets/monkey-idle-2.webp'),
        require('../../../../assets/pets/monkey-idle-3.webp'),
      ],
      width: 240,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/monkey-dirty-0.webp'),
        require('../../../../assets/pets/monkey-dirty-1.webp'),
        require('../../../../assets/pets/monkey-dirty-2.webp'),
        require('../../../../assets/pets/monkey-dirty-3.webp'),
      ],
      width: 236,
      height: 221,
      heightRatio: 1.0045,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/monkey-bath-0.webp'),
        require('../../../../assets/pets/monkey-bath-1.webp'),
        require('../../../../assets/pets/monkey-bath-2.webp'),
        require('../../../../assets/pets/monkey-bath-3.webp'),
        require('../../../../assets/pets/monkey-bath-4.webp'),
        require('../../../../assets/pets/monkey-bath-5.webp'),
      ],
      width: 143,
      height: 164,
      heightRatio: 0.7455,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/monkey-eat-0.webp'),
        require('../../../../assets/pets/monkey-eat-1.webp'),
        require('../../../../assets/pets/monkey-eat-2.webp'),
        require('../../../../assets/pets/monkey-eat-3.webp'),
      ],
      width: 257,
      height: 219,
      heightRatio: 0.9955,
    },
  },
  'cat-adult': {
    idle: {
      frames: [
        require('../../../../assets/pets/cat-adult-idle-0.webp'),
        require('../../../../assets/pets/cat-adult-idle-1.webp'),
        require('../../../../assets/pets/cat-adult-idle-2.webp'),
        require('../../../../assets/pets/cat-adult-idle-3.webp'),
      ],
      width: 200,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/cat-adult-walk-0.webp'),
        require('../../../../assets/pets/cat-adult-walk-1.webp'),
        require('../../../../assets/pets/cat-adult-walk-2.webp'),
        require('../../../../assets/pets/cat-adult-walk-3.webp'),
      ],
      width: 219,
      height: 202,
      heightRatio: 0.9182,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/cat-adult-dirty-0.webp'),
        require('../../../../assets/pets/cat-adult-dirty-1.webp'),
        require('../../../../assets/pets/cat-adult-dirty-2.webp'),
        require('../../../../assets/pets/cat-adult-dirty-3.webp'),
      ],
      width: 242,
      height: 217,
      heightRatio: 0.9864,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/cat-adult-bath-0.png'),
        require('../../../../assets/pets/cat-adult-bath-1.png'),
        require('../../../../assets/pets/cat-adult-bath-2.png'),
        require('../../../../assets/pets/cat-adult-bath-3.png'),
        require('../../../../assets/pets/cat-adult-bath-4.png'),
        require('../../../../assets/pets/cat-adult-bath-5.png'),
      ],
      width: 129,
      height: 143,
      heightRatio: 0.65,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/cat-adult-happy-0.webp'),
        require('../../../../assets/pets/cat-adult-happy-1.webp'),
        require('../../../../assets/pets/cat-adult-happy-2.webp'),
        require('../../../../assets/pets/cat-adult-happy-3.webp'),
      ],
      width: 251,
      height: 255,
      heightRatio: 1.1591,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/cat-adult-eat-0.webp'),
        require('../../../../assets/pets/cat-adult-eat-1.webp'),
        require('../../../../assets/pets/cat-adult-eat-2.webp'),
        require('../../../../assets/pets/cat-adult-eat-3.webp'),
      ],
      width: 252,
      height: 202,
      heightRatio: 0.9182,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/cat-adult-sleep-0.webp'),
        require('../../../../assets/pets/cat-adult-sleep-1.webp'),
        require('../../../../assets/pets/cat-adult-sleep-2.webp'),
        require('../../../../assets/pets/cat-adult-sleep-3.webp'),
      ],
      width: 174,
      height: 134,
      heightRatio: 0.6091,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/cat-adult-ball-0.webp'),
        require('../../../../assets/pets/cat-adult-ball-1.webp'),
        require('../../../../assets/pets/cat-adult-ball-2.webp'),
        require('../../../../assets/pets/cat-adult-ball-3.webp'),
      ],
      width: 164,
      height: 157,
      heightRatio: 0.7136,
    },
    house: {
      frames: [
        require('../../../../assets/pets/cat-adult-house-0.webp'),
        require('../../../../assets/pets/cat-adult-house-1.webp'),
        require('../../../../assets/pets/cat-adult-house-2.webp'),
        require('../../../../assets/pets/cat-adult-house-3.webp'),
      ],
      width: 241,
      height: 170,
      heightRatio: 0.7727,
    },
  },
  'dog-adult': {
    idle: {
      frames: [
        require('../../../../assets/pets/dog-adult-idle-0.webp'),
        require('../../../../assets/pets/dog-adult-idle-1.webp'),
        require('../../../../assets/pets/dog-adult-idle-2.webp'),
        require('../../../../assets/pets/dog-adult-idle-3.webp'),
      ],
      width: 207,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/dog-adult-walk-0.webp'),
        require('../../../../assets/pets/dog-adult-walk-1.webp'),
        require('../../../../assets/pets/dog-adult-walk-2.webp'),
        require('../../../../assets/pets/dog-adult-walk-3.webp'),
      ],
      width: 206,
      height: 176,
      heightRatio: 0.8,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/dog-adult-dirty-0.webp'),
        require('../../../../assets/pets/dog-adult-dirty-1.webp'),
        require('../../../../assets/pets/dog-adult-dirty-2.webp'),
        require('../../../../assets/pets/dog-adult-dirty-3.webp'),
      ],
      width: 205,
      height: 190,
      heightRatio: 0.8636,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/dog-adult-bath-0.png'),
        require('../../../../assets/pets/dog-adult-bath-1.png'),
        require('../../../../assets/pets/dog-adult-bath-2.webp'),
        require('../../../../assets/pets/dog-adult-bath-3.png'),
        require('../../../../assets/pets/dog-adult-bath-4.webp'),
        require('../../../../assets/pets/dog-adult-bath-5.png'),
      ],
      width: 130,
      height: 154,
      heightRatio: 0.7,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/dog-adult-happy-0.webp'),
        require('../../../../assets/pets/dog-adult-happy-1.webp'),
        require('../../../../assets/pets/dog-adult-happy-2.webp'),
        require('../../../../assets/pets/dog-adult-happy-3.webp'),
      ],
      width: 186,
      height: 214,
      heightRatio: 0.9727,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/dog-adult-eat-0.webp'),
        require('../../../../assets/pets/dog-adult-eat-1.webp'),
        require('../../../../assets/pets/dog-adult-eat-2.webp'),
        require('../../../../assets/pets/dog-adult-eat-3.webp'),
      ],
      width: 255,
      height: 194,
      heightRatio: 0.8818,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/dog-adult-sleep-0.webp'),
        require('../../../../assets/pets/dog-adult-sleep-1.webp'),
        require('../../../../assets/pets/dog-adult-sleep-2.webp'),
        require('../../../../assets/pets/dog-adult-sleep-3.webp'),
      ],
      width: 200,
      height: 130,
      heightRatio: 0.5909,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/dog-adult-ball-0.webp'),
        require('../../../../assets/pets/dog-adult-ball-1.webp'),
        require('../../../../assets/pets/dog-adult-ball-2.webp'),
        require('../../../../assets/pets/dog-adult-ball-3.webp'),
      ],
      width: 203,
      height: 183,
      heightRatio: 0.8318,
    },
    house: {
      frames: [
        require('../../../../assets/pets/dog-adult-house-0.webp'),
        require('../../../../assets/pets/dog-adult-house-1.webp'),
        require('../../../../assets/pets/dog-adult-house-2.webp'),
        require('../../../../assets/pets/dog-adult-house-3.webp'),
      ],
      width: 213,
      height: 169,
      heightRatio: 0.7682,
    },
  },
  'pig-adult': {
    idle: {
      frames: [
        require('../../../../assets/pets/pig-adult-idle-0.webp'),
        require('../../../../assets/pets/pig-adult-idle-1.webp'),
        require('../../../../assets/pets/pig-adult-idle-2.webp'),
        require('../../../../assets/pets/pig-adult-idle-3.webp'),
      ],
      width: 242,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/pig-adult-walk-0.webp'),
        require('../../../../assets/pets/pig-adult-walk-1.webp'),
        require('../../../../assets/pets/pig-adult-walk-2.webp'),
        require('../../../../assets/pets/pig-adult-walk-3.webp'),
      ],
      width: 241,
      height: 198,
      heightRatio: 0.9,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/pig-adult-dirty-0.webp'),
        require('../../../../assets/pets/pig-adult-dirty-1.webp'),
        require('../../../../assets/pets/pig-adult-dirty-2.webp'),
        require('../../../../assets/pets/pig-adult-dirty-3.webp'),
      ],
      width: 243,
      height: 203,
      heightRatio: 0.9227,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/pig-adult-bath-0.webp'),
        require('../../../../assets/pets/pig-adult-bath-1.webp'),
        require('../../../../assets/pets/pig-adult-bath-2.webp'),
        require('../../../../assets/pets/pig-adult-bath-3.png'),
        require('../../../../assets/pets/pig-adult-bath-4.png'),
        require('../../../../assets/pets/pig-adult-bath-5.png'),
      ],
      width: 147,
      height: 155,
      heightRatio: 0.7045,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/pig-adult-happy-0.webp'),
        require('../../../../assets/pets/pig-adult-happy-1.webp'),
        require('../../../../assets/pets/pig-adult-happy-2.webp'),
        require('../../../../assets/pets/pig-adult-happy-3.webp'),
      ],
      width: 214,
      height: 232,
      heightRatio: 1.0545,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/pig-adult-eat-0.webp'),
        require('../../../../assets/pets/pig-adult-eat-1.webp'),
        require('../../../../assets/pets/pig-adult-eat-2.webp'),
        require('../../../../assets/pets/pig-adult-eat-3.webp'),
      ],
      width: 240,
      height: 196,
      heightRatio: 0.8909,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/pig-adult-sleep-0.webp'),
        require('../../../../assets/pets/pig-adult-sleep-1.webp'),
        require('../../../../assets/pets/pig-adult-sleep-2.webp'),
        require('../../../../assets/pets/pig-adult-sleep-3.webp'),
      ],
      width: 203,
      height: 143,
      heightRatio: 0.65,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/pig-adult-ball-0.webp'),
        require('../../../../assets/pets/pig-adult-ball-1.webp'),
        require('../../../../assets/pets/pig-adult-ball-2.webp'),
        require('../../../../assets/pets/pig-adult-ball-3.webp'),
      ],
      width: 173,
      height: 136,
      heightRatio: 0.6182,
    },
    house: {
      frames: [
        require('../../../../assets/pets/pig-adult-house-0.webp'),
        require('../../../../assets/pets/pig-adult-house-1.webp'),
        require('../../../../assets/pets/pig-adult-house-2.webp'),
        require('../../../../assets/pets/pig-adult-house-3.webp'),
      ],
      width: 227,
      height: 172,
      heightRatio: 0.7818,
    },
  },
  'monkey-adult': {
    idle: {
      frames: [
        require('../../../../assets/pets/monkey-adult-idle-0.webp'),
        require('../../../../assets/pets/monkey-adult-idle-1.webp'),
        require('../../../../assets/pets/monkey-adult-idle-2.webp'),
        require('../../../../assets/pets/monkey-adult-idle-3.webp'),
      ],
      width: 213,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/monkey-adult-walk-0.webp'),
        require('../../../../assets/pets/monkey-adult-walk-1.webp'),
        require('../../../../assets/pets/monkey-adult-walk-2.webp'),
        require('../../../../assets/pets/monkey-adult-walk-3.webp'),
      ],
      width: 212,
      height: 213,
      heightRatio: 0.9682,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/monkey-adult-dirty-0.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-1.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-2.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-3.webp'),
      ],
      width: 212,
      height: 219,
      heightRatio: 0.9955,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/monkey-adult-bath-0.webp'),
        require('../../../../assets/pets/monkey-adult-bath-1.webp'),
        require('../../../../assets/pets/monkey-adult-bath-2.webp'),
        require('../../../../assets/pets/monkey-adult-bath-3.webp'),
        require('../../../../assets/pets/monkey-adult-bath-4.webp'),
        require('../../../../assets/pets/monkey-adult-bath-5.webp'),
      ],
      width: 143,
      height: 164,
      heightRatio: 0.7455,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/monkey-adult-happy-0.webp'),
        require('../../../../assets/pets/monkey-adult-happy-1.webp'),
        require('../../../../assets/pets/monkey-adult-happy-2.webp'),
        require('../../../../assets/pets/monkey-adult-happy-3.webp'),
      ],
      width: 191,
      height: 231,
      heightRatio: 1.05,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/monkey-adult-eat-0.webp'),
        require('../../../../assets/pets/monkey-adult-eat-1.webp'),
        require('../../../../assets/pets/monkey-adult-eat-2.webp'),
        require('../../../../assets/pets/monkey-adult-eat-3.webp'),
      ],
      width: 232,
      height: 219,
      heightRatio: 0.9955,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/monkey-adult-sleep-0.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-1.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-2.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-3.webp'),
      ],
      width: 185,
      height: 146,
      heightRatio: 0.6636,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/monkey-adult-ball-0.webp'),
        require('../../../../assets/pets/monkey-adult-ball-1.webp'),
        require('../../../../assets/pets/monkey-adult-ball-2.webp'),
        require('../../../../assets/pets/monkey-adult-ball-3.webp'),
      ],
      width: 176,
      height: 193,
      heightRatio: 0.8773,
    },
    house: {
      frames: [
        require('../../../../assets/pets/monkey-adult-house-0.webp'),
        require('../../../../assets/pets/monkey-adult-house-1.webp'),
        require('../../../../assets/pets/monkey-adult-house-2.webp'),
        require('../../../../assets/pets/monkey-adult-house-3.webp'),
      ],
      width: 226,
      height: 170,
      heightRatio: 0.7727,
    },
  },
  'cat--black': {
    sleep: {
      frames: [
        require('../../../../assets/pets/cat-sleep-0--black.png'),
        require('../../../../assets/pets/cat-sleep-1--black.png'),
        require('../../../../assets/pets/cat-sleep-2--black.png'),
        require('../../../../assets/pets/cat-sleep-3--black.png'),
      ],
      width: 161,
      height: 141,
      heightRatio: 0.6409,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/cat-ball-0--black.webp'),
        require('../../../../assets/pets/cat-ball-1--black.webp'),
        require('../../../../assets/pets/cat-ball-2--black.webp'),
        require('../../../../assets/pets/cat-ball-3--black.webp'),
      ],
      width: 159,
      height: 223,
      heightRatio: 1.0136,
    },
    house: {
      frames: [
        require('../../../../assets/pets/cat-house-0--black.webp'),
        require('../../../../assets/pets/cat-house-1--black.png'),
        require('../../../../assets/pets/cat-house-2--black.webp'),
        require('../../../../assets/pets/cat-house-3--black.webp'),
      ],
      width: 204,
      height: 171,
      heightRatio: 0.7773,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/cat-eat-0--black.webp'),
        require('../../../../assets/pets/cat-eat-1--black.webp'),
        require('../../../../assets/pets/cat-eat-2--black.webp'),
        require('../../../../assets/pets/cat-eat-3--black.webp'),
      ],
      width: 224,
      height: 190,
      heightRatio: 0.8636,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/cat-happy-0--black.webp'),
        require('../../../../assets/pets/cat-happy-1--black.webp'),
        require('../../../../assets/pets/cat-happy-2--black.webp'),
        require('../../../../assets/pets/cat-happy-3--black.webp'),
      ],
      width: 221,
      height: 206,
      heightRatio: 0.9364,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/cat-walk-0--black.webp'),
        require('../../../../assets/pets/cat-walk-1--black.webp'),
        require('../../../../assets/pets/cat-walk-2--black.webp'),
        require('../../../../assets/pets/cat-walk-3--black.webp'),
      ],
      width: 218,
      height: 199,
      heightRatio: 0.9045,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/cat-idle-0--black.webp'),
        require('../../../../assets/pets/cat-idle-1--black.webp'),
        require('../../../../assets/pets/cat-idle-2--black.webp'),
        require('../../../../assets/pets/cat-idle-3--black.webp'),
      ],
      width: 202,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/cat-dirty-0--black.png'),
        require('../../../../assets/pets/cat-dirty-1--black.png'),
        require('../../../../assets/pets/cat-dirty-2--black.png'),
        require('../../../../assets/pets/cat-dirty-3--black.png'),
      ],
      width: 218,
      height: 199,
      heightRatio: 0.9045,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/cat-bath-0--black.png'),
        require('../../../../assets/pets/cat-bath-1--black.png'),
        require('../../../../assets/pets/cat-bath-2--black.webp'),
        require('../../../../assets/pets/cat-bath-3--black.png'),
        require('../../../../assets/pets/cat-bath-4--black.png'),
        require('../../../../assets/pets/cat-bath-5--black.png'),
      ],
      width: 140,
      height: 142,
      heightRatio: 0.6455,
    },
  },
  'cat--brown': {
    sleep: {
      frames: [
        require('../../../../assets/pets/cat-sleep-0--brown.webp'),
        require('../../../../assets/pets/cat-sleep-1--brown.webp'),
        require('../../../../assets/pets/cat-sleep-2--brown.webp'),
        require('../../../../assets/pets/cat-sleep-3--brown.webp'),
      ],
      width: 161,
      height: 141,
      heightRatio: 0.6409,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/cat-ball-0--brown.webp'),
        require('../../../../assets/pets/cat-ball-1--brown.webp'),
        require('../../../../assets/pets/cat-ball-2--brown.webp'),
        require('../../../../assets/pets/cat-ball-3--brown.webp'),
      ],
      width: 159,
      height: 223,
      heightRatio: 1.0136,
    },
    house: {
      frames: [
        require('../../../../assets/pets/cat-house-0--brown.webp'),
        require('../../../../assets/pets/cat-house-1--brown.png'),
        require('../../../../assets/pets/cat-house-2--brown.webp'),
        require('../../../../assets/pets/cat-house-3--brown.webp'),
      ],
      width: 204,
      height: 171,
      heightRatio: 0.7773,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/cat-eat-0--brown.webp'),
        require('../../../../assets/pets/cat-eat-1--brown.webp'),
        require('../../../../assets/pets/cat-eat-2--brown.webp'),
        require('../../../../assets/pets/cat-eat-3--brown.webp'),
      ],
      width: 224,
      height: 190,
      heightRatio: 0.8636,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/cat-happy-0--brown.webp'),
        require('../../../../assets/pets/cat-happy-1--brown.webp'),
        require('../../../../assets/pets/cat-happy-2--brown.webp'),
        require('../../../../assets/pets/cat-happy-3--brown.webp'),
      ],
      width: 221,
      height: 206,
      heightRatio: 0.9364,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/cat-walk-0--brown.webp'),
        require('../../../../assets/pets/cat-walk-1--brown.webp'),
        require('../../../../assets/pets/cat-walk-2--brown.webp'),
        require('../../../../assets/pets/cat-walk-3--brown.webp'),
      ],
      width: 218,
      height: 199,
      heightRatio: 0.9045,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/cat-idle-0--brown.webp'),
        require('../../../../assets/pets/cat-idle-1--brown.webp'),
        require('../../../../assets/pets/cat-idle-2--brown.webp'),
        require('../../../../assets/pets/cat-idle-3--brown.webp'),
      ],
      width: 202,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/cat-dirty-0--brown.webp'),
        require('../../../../assets/pets/cat-dirty-1--brown.webp'),
        require('../../../../assets/pets/cat-dirty-2--brown.webp'),
        require('../../../../assets/pets/cat-dirty-3--brown.webp'),
      ],
      width: 218,
      height: 199,
      heightRatio: 0.9045,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/cat-bath-0--brown.webp'),
        require('../../../../assets/pets/cat-bath-1--brown.webp'),
        require('../../../../assets/pets/cat-bath-2--brown.webp'),
        require('../../../../assets/pets/cat-bath-3--brown.png'),
        require('../../../../assets/pets/cat-bath-4--brown.webp'),
        require('../../../../assets/pets/cat-bath-5--brown.png'),
      ],
      width: 140,
      height: 142,
      heightRatio: 0.6455,
    },
  },
  'dog--black': {
    sleep: {
      frames: [
        require('../../../../assets/pets/dog-sleep-0--black.webp'),
        require('../../../../assets/pets/dog-sleep-1--black.webp'),
        require('../../../../assets/pets/dog-sleep-2--black.webp'),
        require('../../../../assets/pets/dog-sleep-3--black.webp'),
      ],
      width: 178,
      height: 130,
      heightRatio: 0.5909,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/dog-ball-0--black.webp'),
        require('../../../../assets/pets/dog-ball-1--black.webp'),
        require('../../../../assets/pets/dog-ball-2--black.webp'),
        require('../../../../assets/pets/dog-ball-3--black.webp'),
      ],
      width: 172,
      height: 230,
      heightRatio: 1.0455,
    },
    house: {
      frames: [
        require('../../../../assets/pets/dog-house-0--black.webp'),
        require('../../../../assets/pets/dog-house-1--black.png'),
        require('../../../../assets/pets/dog-house-2--black.webp'),
        require('../../../../assets/pets/dog-house-3--black.webp'),
      ],
      width: 213,
      height: 169,
      heightRatio: 0.7682,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/dog-happy-0--black.webp'),
        require('../../../../assets/pets/dog-happy-1--black.webp'),
        require('../../../../assets/pets/dog-happy-2--black.webp'),
        require('../../../../assets/pets/dog-happy-3--black.webp'),
      ],
      width: 225,
      height: 214,
      heightRatio: 0.9727,
    },
    play: {
      frames: [
        require('../../../../assets/pets/dog-play-0--black.webp'),
        require('../../../../assets/pets/dog-play-1--black.webp'),
        require('../../../../assets/pets/dog-play-2--black.webp'),
        require('../../../../assets/pets/dog-play-3--black.webp'),
      ],
      width: 249,
      height: 162,
      heightRatio: 0.7364,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/dog-eat-0--black.webp'),
        require('../../../../assets/pets/dog-eat-1--black.webp'),
        require('../../../../assets/pets/dog-eat-2--black.webp'),
        require('../../../../assets/pets/dog-eat-3--black.webp'),
      ],
      width: 263,
      height: 194,
      heightRatio: 0.8818,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/dog-walk-0--black.webp'),
        require('../../../../assets/pets/dog-walk-1--black.webp'),
        require('../../../../assets/pets/dog-walk-2--black.webp'),
        require('../../../../assets/pets/dog-walk-3--black.webp'),
      ],
      width: 236,
      height: 204,
      heightRatio: 0.9273,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/dog-idle-0--black.webp'),
        require('../../../../assets/pets/dog-idle-1--black.webp'),
        require('../../../../assets/pets/dog-idle-2--black.webp'),
        require('../../../../assets/pets/dog-idle-3--black.webp'),
      ],
      width: 225,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/dog-dirty-0--black.png'),
        require('../../../../assets/pets/dog-dirty-1--black.png'),
        require('../../../../assets/pets/dog-dirty-2--black.png'),
        require('../../../../assets/pets/dog-dirty-3--black.png'),
      ],
      width: 236,
      height: 204,
      heightRatio: 0.9273,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/dog-bath-0--black.png'),
        require('../../../../assets/pets/dog-bath-1--black.png'),
        require('../../../../assets/pets/dog-bath-2--black.webp'),
        require('../../../../assets/pets/dog-bath-3--black.png'),
        require('../../../../assets/pets/dog-bath-4--black.png'),
        require('../../../../assets/pets/dog-bath-5--black.png'),
      ],
      width: 143,
      height: 154,
      heightRatio: 0.7,
    },
  },
  'dog--brown': {
    sleep: {
      frames: [
        require('../../../../assets/pets/dog-sleep-0--brown.webp'),
        require('../../../../assets/pets/dog-sleep-1--brown.webp'),
        require('../../../../assets/pets/dog-sleep-2--brown.webp'),
        require('../../../../assets/pets/dog-sleep-3--brown.webp'),
      ],
      width: 178,
      height: 130,
      heightRatio: 0.5909,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/dog-ball-0--brown.webp'),
        require('../../../../assets/pets/dog-ball-1--brown.webp'),
        require('../../../../assets/pets/dog-ball-2--brown.webp'),
        require('../../../../assets/pets/dog-ball-3--brown.webp'),
      ],
      width: 172,
      height: 230,
      heightRatio: 1.0455,
    },
    house: {
      frames: [
        require('../../../../assets/pets/dog-house-0--brown.webp'),
        require('../../../../assets/pets/dog-house-1--brown.webp'),
        require('../../../../assets/pets/dog-house-2--brown.webp'),
        require('../../../../assets/pets/dog-house-3--brown.webp'),
      ],
      width: 213,
      height: 169,
      heightRatio: 0.7682,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/dog-happy-0--brown.webp'),
        require('../../../../assets/pets/dog-happy-1--brown.webp'),
        require('../../../../assets/pets/dog-happy-2--brown.webp'),
        require('../../../../assets/pets/dog-happy-3--brown.webp'),
      ],
      width: 225,
      height: 214,
      heightRatio: 0.9727,
    },
    play: {
      frames: [
        require('../../../../assets/pets/dog-play-0--brown.webp'),
        require('../../../../assets/pets/dog-play-1--brown.webp'),
        require('../../../../assets/pets/dog-play-2--brown.webp'),
        require('../../../../assets/pets/dog-play-3--brown.webp'),
      ],
      width: 249,
      height: 162,
      heightRatio: 0.7364,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/dog-eat-0--brown.webp'),
        require('../../../../assets/pets/dog-eat-1--brown.webp'),
        require('../../../../assets/pets/dog-eat-2--brown.webp'),
        require('../../../../assets/pets/dog-eat-3--brown.webp'),
      ],
      width: 263,
      height: 194,
      heightRatio: 0.8818,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/dog-walk-0--brown.webp'),
        require('../../../../assets/pets/dog-walk-1--brown.webp'),
        require('../../../../assets/pets/dog-walk-2--brown.webp'),
        require('../../../../assets/pets/dog-walk-3--brown.webp'),
      ],
      width: 236,
      height: 204,
      heightRatio: 0.9273,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/dog-idle-0--brown.webp'),
        require('../../../../assets/pets/dog-idle-1--brown.webp'),
        require('../../../../assets/pets/dog-idle-2--brown.webp'),
        require('../../../../assets/pets/dog-idle-3--brown.webp'),
      ],
      width: 225,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/dog-dirty-0--brown.webp'),
        require('../../../../assets/pets/dog-dirty-1--brown.webp'),
        require('../../../../assets/pets/dog-dirty-2--brown.webp'),
        require('../../../../assets/pets/dog-dirty-3--brown.png'),
      ],
      width: 236,
      height: 204,
      heightRatio: 0.9273,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/dog-bath-0--brown.png'),
        require('../../../../assets/pets/dog-bath-1--brown.png'),
        require('../../../../assets/pets/dog-bath-2--brown.webp'),
        require('../../../../assets/pets/dog-bath-3--brown.png'),
        require('../../../../assets/pets/dog-bath-4--brown.png'),
        require('../../../../assets/pets/dog-bath-5--brown.png'),
      ],
      width: 143,
      height: 154,
      heightRatio: 0.7,
    },
  },
  'pig--black': {
    sleep: {
      frames: [
        require('../../../../assets/pets/pig-sleep-0--black.webp'),
        require('../../../../assets/pets/pig-sleep-1--black.webp'),
        require('../../../../assets/pets/pig-sleep-2--black.png'),
        require('../../../../assets/pets/pig-sleep-3--black.webp'),
      ],
      width: 185,
      height: 143,
      heightRatio: 0.65,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/pig-ball-0--black.webp'),
        require('../../../../assets/pets/pig-ball-1--black.webp'),
        require('../../../../assets/pets/pig-ball-2--black.webp'),
        require('../../../../assets/pets/pig-ball-3--black.webp'),
      ],
      width: 178,
      height: 193,
      heightRatio: 0.8773,
    },
    house: {
      frames: [
        require('../../../../assets/pets/pig-house-0--black.webp'),
        require('../../../../assets/pets/pig-house-1--black.png'),
        require('../../../../assets/pets/pig-house-2--black.webp'),
        require('../../../../assets/pets/pig-house-3--black.webp'),
      ],
      width: 215,
      height: 171,
      heightRatio: 0.7773,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/pig-idle-0--black.webp'),
        require('../../../../assets/pets/pig-idle-1--black.webp'),
        require('../../../../assets/pets/pig-idle-2--black.webp'),
        require('../../../../assets/pets/pig-idle-3--black.webp'),
      ],
      width: 236,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/pig-dirty-0--black.png'),
        require('../../../../assets/pets/pig-dirty-1--black.webp'),
        require('../../../../assets/pets/pig-dirty-2--black.webp'),
        require('../../../../assets/pets/pig-dirty-3--black.webp'),
      ],
      width: 225,
      height: 206,
      heightRatio: 0.9364,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/pig-bath-0--black.png'),
        require('../../../../assets/pets/pig-bath-1--black.png'),
        require('../../../../assets/pets/pig-bath-2--black.webp'),
        require('../../../../assets/pets/pig-bath-3--black.png'),
        require('../../../../assets/pets/pig-bath-4--black.png'),
        require('../../../../assets/pets/pig-bath-5--black.png'),
      ],
      width: 135,
      height: 155,
      heightRatio: 0.7045,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/pig-walk-0--black.webp'),
        require('../../../../assets/pets/pig-walk-1--black.webp'),
        require('../../../../assets/pets/pig-walk-2--black.webp'),
        require('../../../../assets/pets/pig-walk-3--black.webp'),
      ],
      width: 225,
      height: 206,
      heightRatio: 0.9364,
    },
    play: {
      frames: [
        require('../../../../assets/pets/pig-play-0--black.webp'),
        require('../../../../assets/pets/pig-play-1--black.webp'),
        require('../../../../assets/pets/pig-play-2--black.webp'),
        require('../../../../assets/pets/pig-play-3--black.webp'),
      ],
      width: 236,
      height: 224,
      heightRatio: 1.0182,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/pig-happy-0--black.webp'),
        require('../../../../assets/pets/pig-happy-1--black.webp'),
        require('../../../../assets/pets/pig-happy-2--black.webp'),
        require('../../../../assets/pets/pig-happy-3--black.webp'),
      ],
      width: 229,
      height: 232,
      heightRatio: 1.0545,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/pig-eat-0--black.webp'),
        require('../../../../assets/pets/pig-eat-1--black.webp'),
        require('../../../../assets/pets/pig-eat-2--black.webp'),
        require('../../../../assets/pets/pig-eat-3--black.webp'),
      ],
      width: 254,
      height: 197,
      heightRatio: 0.8955,
    },
  },
  'pig--brown': {
    sleep: {
      frames: [
        require('../../../../assets/pets/pig-sleep-0--brown.webp'),
        require('../../../../assets/pets/pig-sleep-1--brown.webp'),
        require('../../../../assets/pets/pig-sleep-2--brown.webp'),
        require('../../../../assets/pets/pig-sleep-3--brown.webp'),
      ],
      width: 185,
      height: 143,
      heightRatio: 0.65,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/pig-ball-0--brown.webp'),
        require('../../../../assets/pets/pig-ball-1--brown.webp'),
        require('../../../../assets/pets/pig-ball-2--brown.webp'),
        require('../../../../assets/pets/pig-ball-3--brown.webp'),
      ],
      width: 178,
      height: 193,
      heightRatio: 0.8773,
    },
    house: {
      frames: [
        require('../../../../assets/pets/pig-house-0--brown.webp'),
        require('../../../../assets/pets/pig-house-1--brown.webp'),
        require('../../../../assets/pets/pig-house-2--brown.webp'),
        require('../../../../assets/pets/pig-house-3--brown.webp'),
      ],
      width: 215,
      height: 171,
      heightRatio: 0.7773,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/pig-idle-0--brown.webp'),
        require('../../../../assets/pets/pig-idle-1--brown.webp'),
        require('../../../../assets/pets/pig-idle-2--brown.webp'),
        require('../../../../assets/pets/pig-idle-3--brown.webp'),
      ],
      width: 236,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/pig-dirty-0--brown.webp'),
        require('../../../../assets/pets/pig-dirty-1--brown.webp'),
        require('../../../../assets/pets/pig-dirty-2--brown.webp'),
        require('../../../../assets/pets/pig-dirty-3--brown.webp'),
      ],
      width: 225,
      height: 206,
      heightRatio: 0.9364,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/pig-bath-0--brown.png'),
        require('../../../../assets/pets/pig-bath-1--brown.png'),
        require('../../../../assets/pets/pig-bath-2--brown.webp'),
        require('../../../../assets/pets/pig-bath-3--brown.png'),
        require('../../../../assets/pets/pig-bath-4--brown.png'),
        require('../../../../assets/pets/pig-bath-5--brown.png'),
      ],
      width: 135,
      height: 155,
      heightRatio: 0.7045,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/pig-walk-0--brown.webp'),
        require('../../../../assets/pets/pig-walk-1--brown.webp'),
        require('../../../../assets/pets/pig-walk-2--brown.webp'),
        require('../../../../assets/pets/pig-walk-3--brown.webp'),
      ],
      width: 225,
      height: 206,
      heightRatio: 0.9364,
    },
    play: {
      frames: [
        require('../../../../assets/pets/pig-play-0--brown.webp'),
        require('../../../../assets/pets/pig-play-1--brown.webp'),
        require('../../../../assets/pets/pig-play-2--brown.webp'),
        require('../../../../assets/pets/pig-play-3--brown.webp'),
      ],
      width: 236,
      height: 224,
      heightRatio: 1.0182,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/pig-happy-0--brown.webp'),
        require('../../../../assets/pets/pig-happy-1--brown.webp'),
        require('../../../../assets/pets/pig-happy-2--brown.webp'),
        require('../../../../assets/pets/pig-happy-3--brown.webp'),
      ],
      width: 229,
      height: 232,
      heightRatio: 1.0545,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/pig-eat-0--brown.webp'),
        require('../../../../assets/pets/pig-eat-1--brown.webp'),
        require('../../../../assets/pets/pig-eat-2--brown.webp'),
        require('../../../../assets/pets/pig-eat-3--brown.webp'),
      ],
      width: 254,
      height: 197,
      heightRatio: 0.8955,
    },
  },
  'monkey--black': {
    sleep: {
      frames: [
        require('../../../../assets/pets/monkey-sleep-0--black.webp'),
        require('../../../../assets/pets/monkey-sleep-1--black.webp'),
        require('../../../../assets/pets/monkey-sleep-2--black.webp'),
        require('../../../../assets/pets/monkey-sleep-3--black.png'),
      ],
      width: 173,
      height: 146,
      heightRatio: 0.6636,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/monkey-ball-0--black.webp'),
        require('../../../../assets/pets/monkey-ball-1--black.webp'),
        require('../../../../assets/pets/monkey-ball-2--black.webp'),
        require('../../../../assets/pets/monkey-ball-3--black.webp'),
      ],
      width: 173,
      height: 244,
      heightRatio: 1.1091,
    },
    house: {
      frames: [
        require('../../../../assets/pets/monkey-house-0--black.webp'),
        require('../../../../assets/pets/monkey-house-1--black.png'),
        require('../../../../assets/pets/monkey-house-2--black.webp'),
        require('../../../../assets/pets/monkey-house-3--black.webp'),
      ],
      width: 215,
      height: 170,
      heightRatio: 0.7727,
    },
    play: {
      frames: [
        require('../../../../assets/pets/monkey-play-0--black.webp'),
        require('../../../../assets/pets/monkey-play-1--black.webp'),
        require('../../../../assets/pets/monkey-play-2--black.webp'),
        require('../../../../assets/pets/monkey-play-3--black.webp'),
      ],
      width: 256,
      height: 238,
      heightRatio: 1.0818,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/monkey-happy-0--black.webp'),
        require('../../../../assets/pets/monkey-happy-1--black.webp'),
        require('../../../../assets/pets/monkey-happy-2--black.webp'),
        require('../../../../assets/pets/monkey-happy-3--black.webp'),
      ],
      width: 239,
      height: 231,
      heightRatio: 1.05,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/monkey-walk-0--black.webp'),
        require('../../../../assets/pets/monkey-walk-1--black.webp'),
        require('../../../../assets/pets/monkey-walk-2--black.webp'),
        require('../../../../assets/pets/monkey-walk-3--black.webp'),
      ],
      width: 236,
      height: 221,
      heightRatio: 1.0045,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/monkey-idle-0--black.webp'),
        require('../../../../assets/pets/monkey-idle-1--black.webp'),
        require('../../../../assets/pets/monkey-idle-2--black.webp'),
        require('../../../../assets/pets/monkey-idle-3--black.webp'),
      ],
      width: 240,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/monkey-dirty-0--black.webp'),
        require('../../../../assets/pets/monkey-dirty-1--black.png'),
        require('../../../../assets/pets/monkey-dirty-2--black.png'),
        require('../../../../assets/pets/monkey-dirty-3--black.png'),
      ],
      width: 236,
      height: 221,
      heightRatio: 1.0045,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/monkey-bath-0--black.png'),
        require('../../../../assets/pets/monkey-bath-1--black.png'),
        require('../../../../assets/pets/monkey-bath-2--black.webp'),
        require('../../../../assets/pets/monkey-bath-3--black.png'),
        require('../../../../assets/pets/monkey-bath-4--black.png'),
        require('../../../../assets/pets/monkey-bath-5--black.png'),
      ],
      width: 143,
      height: 164,
      heightRatio: 0.7455,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/monkey-eat-0--black.webp'),
        require('../../../../assets/pets/monkey-eat-1--black.webp'),
        require('../../../../assets/pets/monkey-eat-2--black.webp'),
        require('../../../../assets/pets/monkey-eat-3--black.webp'),
      ],
      width: 257,
      height: 219,
      heightRatio: 0.9955,
    },
  },
  'monkey--brown': {
    sleep: {
      frames: [
        require('../../../../assets/pets/monkey-sleep-0--brown.webp'),
        require('../../../../assets/pets/monkey-sleep-1--brown.webp'),
        require('../../../../assets/pets/monkey-sleep-2--brown.webp'),
        require('../../../../assets/pets/monkey-sleep-3--brown.webp'),
      ],
      width: 173,
      height: 146,
      heightRatio: 0.6636,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/monkey-ball-0--brown.webp'),
        require('../../../../assets/pets/monkey-ball-1--brown.webp'),
        require('../../../../assets/pets/monkey-ball-2--brown.webp'),
        require('../../../../assets/pets/monkey-ball-3--brown.webp'),
      ],
      width: 173,
      height: 244,
      heightRatio: 1.1091,
    },
    house: {
      frames: [
        require('../../../../assets/pets/monkey-house-0--brown.webp'),
        require('../../../../assets/pets/monkey-house-1--brown.png'),
        require('../../../../assets/pets/monkey-house-2--brown.webp'),
        require('../../../../assets/pets/monkey-house-3--brown.webp'),
      ],
      width: 215,
      height: 170,
      heightRatio: 0.7727,
    },
    play: {
      frames: [
        require('../../../../assets/pets/monkey-play-0--brown.webp'),
        require('../../../../assets/pets/monkey-play-1--brown.webp'),
        require('../../../../assets/pets/monkey-play-2--brown.webp'),
        require('../../../../assets/pets/monkey-play-3--brown.webp'),
      ],
      width: 256,
      height: 238,
      heightRatio: 1.0818,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/monkey-happy-0--brown.webp'),
        require('../../../../assets/pets/monkey-happy-1--brown.webp'),
        require('../../../../assets/pets/monkey-happy-2--brown.webp'),
        require('../../../../assets/pets/monkey-happy-3--brown.webp'),
      ],
      width: 239,
      height: 231,
      heightRatio: 1.05,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/monkey-walk-0--brown.webp'),
        require('../../../../assets/pets/monkey-walk-1--brown.webp'),
        require('../../../../assets/pets/monkey-walk-2--brown.webp'),
        require('../../../../assets/pets/monkey-walk-3--brown.webp'),
      ],
      width: 236,
      height: 221,
      heightRatio: 1.0045,
    },
    idle: {
      frames: [
        require('../../../../assets/pets/monkey-idle-0--brown.webp'),
        require('../../../../assets/pets/monkey-idle-1--brown.webp'),
        require('../../../../assets/pets/monkey-idle-2--brown.webp'),
        require('../../../../assets/pets/monkey-idle-3--brown.webp'),
      ],
      width: 240,
      height: 220,
      heightRatio: 1.0,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/monkey-dirty-0--brown.webp'),
        require('../../../../assets/pets/monkey-dirty-1--brown.webp'),
        require('../../../../assets/pets/monkey-dirty-2--brown.webp'),
        require('../../../../assets/pets/monkey-dirty-3--brown.webp'),
      ],
      width: 236,
      height: 221,
      heightRatio: 1.0045,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/monkey-bath-0--brown.png'),
        require('../../../../assets/pets/monkey-bath-1--brown.webp'),
        require('../../../../assets/pets/monkey-bath-2--brown.webp'),
        require('../../../../assets/pets/monkey-bath-3--brown.webp'),
        require('../../../../assets/pets/monkey-bath-4--brown.png'),
        require('../../../../assets/pets/monkey-bath-5--brown.png'),
      ],
      width: 143,
      height: 164,
      heightRatio: 0.7455,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/monkey-eat-0--brown.webp'),
        require('../../../../assets/pets/monkey-eat-1--brown.webp'),
        require('../../../../assets/pets/monkey-eat-2--brown.webp'),
        require('../../../../assets/pets/monkey-eat-3--brown.webp'),
      ],
      width: 257,
      height: 219,
      heightRatio: 0.9955,
    },
  },
  'cat-adult--black': {
    idle: {
      frames: [
        require('../../../../assets/pets/cat-adult-idle-0--black.webp'),
        require('../../../../assets/pets/cat-adult-idle-1--black.webp'),
        require('../../../../assets/pets/cat-adult-idle-2--black.webp'),
        require('../../../../assets/pets/cat-adult-idle-3--black.webp'),
      ],
      width: 200,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/cat-adult-walk-0--black.webp'),
        require('../../../../assets/pets/cat-adult-walk-1--black.webp'),
        require('../../../../assets/pets/cat-adult-walk-2--black.webp'),
        require('../../../../assets/pets/cat-adult-walk-3--black.webp'),
      ],
      width: 219,
      height: 202,
      heightRatio: 0.9182,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/cat-adult-dirty-0--black.webp'),
        require('../../../../assets/pets/cat-adult-dirty-1--black.webp'),
        require('../../../../assets/pets/cat-adult-dirty-2--black.webp'),
        require('../../../../assets/pets/cat-adult-dirty-3--black.webp'),
      ],
      width: 242,
      height: 217,
      heightRatio: 0.9864,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/cat-adult-bath-0--black.png'),
        require('../../../../assets/pets/cat-adult-bath-1--black.png'),
        require('../../../../assets/pets/cat-adult-bath-2--black.png'),
        require('../../../../assets/pets/cat-adult-bath-3--black.png'),
        require('../../../../assets/pets/cat-adult-bath-4--black.png'),
        require('../../../../assets/pets/cat-adult-bath-5--black.png'),
      ],
      width: 129,
      height: 143,
      heightRatio: 0.65,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/cat-adult-happy-0--black.webp'),
        require('../../../../assets/pets/cat-adult-happy-1--black.webp'),
        require('../../../../assets/pets/cat-adult-happy-2--black.webp'),
        require('../../../../assets/pets/cat-adult-happy-3--black.webp'),
      ],
      width: 251,
      height: 255,
      heightRatio: 1.1591,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/cat-adult-eat-0--black.webp'),
        require('../../../../assets/pets/cat-adult-eat-1--black.webp'),
        require('../../../../assets/pets/cat-adult-eat-2--black.webp'),
        require('../../../../assets/pets/cat-adult-eat-3--black.webp'),
      ],
      width: 252,
      height: 202,
      heightRatio: 0.9182,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/cat-adult-sleep-0--black.png'),
        require('../../../../assets/pets/cat-adult-sleep-1--black.png'),
        require('../../../../assets/pets/cat-adult-sleep-2--black.png'),
        require('../../../../assets/pets/cat-adult-sleep-3--black.png'),
      ],
      width: 174,
      height: 134,
      heightRatio: 0.6091,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/cat-adult-ball-0--black.png'),
        require('../../../../assets/pets/cat-adult-ball-1--black.png'),
        require('../../../../assets/pets/cat-adult-ball-2--black.png'),
        require('../../../../assets/pets/cat-adult-ball-3--black.png'),
      ],
      width: 164,
      height: 157,
      heightRatio: 0.7136,
    },
    house: {
      frames: [
        require('../../../../assets/pets/cat-adult-house-0--black.webp'),
        require('../../../../assets/pets/cat-adult-house-1--black.webp'),
        require('../../../../assets/pets/cat-adult-house-2--black.webp'),
        require('../../../../assets/pets/cat-adult-house-3--black.webp'),
      ],
      width: 241,
      height: 170,
      heightRatio: 0.7727,
    },
  },
  'cat-adult--brown': {
    idle: {
      frames: [
        require('../../../../assets/pets/cat-adult-idle-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-idle-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-idle-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-idle-3--brown.webp'),
      ],
      width: 200,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/cat-adult-walk-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-walk-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-walk-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-walk-3--brown.webp'),
      ],
      width: 219,
      height: 202,
      heightRatio: 0.9182,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/cat-adult-dirty-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-dirty-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-dirty-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-dirty-3--brown.webp'),
      ],
      width: 242,
      height: 217,
      heightRatio: 0.9864,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/cat-adult-bath-0--brown.png'),
        require('../../../../assets/pets/cat-adult-bath-1--brown.png'),
        require('../../../../assets/pets/cat-adult-bath-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-bath-3--brown.png'),
        require('../../../../assets/pets/cat-adult-bath-4--brown.png'),
        require('../../../../assets/pets/cat-adult-bath-5--brown.png'),
      ],
      width: 129,
      height: 143,
      heightRatio: 0.65,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/cat-adult-happy-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-happy-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-happy-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-happy-3--brown.webp'),
      ],
      width: 251,
      height: 255,
      heightRatio: 1.1591,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/cat-adult-eat-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-eat-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-eat-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-eat-3--brown.webp'),
      ],
      width: 252,
      height: 202,
      heightRatio: 0.9182,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/cat-adult-sleep-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-sleep-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-sleep-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-sleep-3--brown.png'),
      ],
      width: 174,
      height: 134,
      heightRatio: 0.6091,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/cat-adult-ball-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-ball-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-ball-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-ball-3--brown.webp'),
      ],
      width: 164,
      height: 157,
      heightRatio: 0.7136,
    },
    house: {
      frames: [
        require('../../../../assets/pets/cat-adult-house-0--brown.webp'),
        require('../../../../assets/pets/cat-adult-house-1--brown.webp'),
        require('../../../../assets/pets/cat-adult-house-2--brown.webp'),
        require('../../../../assets/pets/cat-adult-house-3--brown.webp'),
      ],
      width: 241,
      height: 170,
      heightRatio: 0.7727,
    },
  },
  'dog-adult--black': {
    idle: {
      frames: [
        require('../../../../assets/pets/dog-adult-idle-0--black.webp'),
        require('../../../../assets/pets/dog-adult-idle-1--black.webp'),
        require('../../../../assets/pets/dog-adult-idle-2--black.webp'),
        require('../../../../assets/pets/dog-adult-idle-3--black.webp'),
      ],
      width: 207,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/dog-adult-walk-0--black.webp'),
        require('../../../../assets/pets/dog-adult-walk-1--black.webp'),
        require('../../../../assets/pets/dog-adult-walk-2--black.webp'),
        require('../../../../assets/pets/dog-adult-walk-3--black.webp'),
      ],
      width: 206,
      height: 176,
      heightRatio: 0.8,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/dog-adult-dirty-0--black.webp'),
        require('../../../../assets/pets/dog-adult-dirty-1--black.webp'),
        require('../../../../assets/pets/dog-adult-dirty-2--black.webp'),
        require('../../../../assets/pets/dog-adult-dirty-3--black.webp'),
      ],
      width: 205,
      height: 190,
      heightRatio: 0.8636,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/dog-adult-bath-0--black.png'),
        require('../../../../assets/pets/dog-adult-bath-1--black.png'),
        require('../../../../assets/pets/dog-adult-bath-2--black.webp'),
        require('../../../../assets/pets/dog-adult-bath-3--black.png'),
        require('../../../../assets/pets/dog-adult-bath-4--black.png'),
        require('../../../../assets/pets/dog-adult-bath-5--black.png'),
      ],
      width: 130,
      height: 154,
      heightRatio: 0.7,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/dog-adult-happy-0--black.webp'),
        require('../../../../assets/pets/dog-adult-happy-1--black.webp'),
        require('../../../../assets/pets/dog-adult-happy-2--black.webp'),
        require('../../../../assets/pets/dog-adult-happy-3--black.webp'),
      ],
      width: 186,
      height: 214,
      heightRatio: 0.9727,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/dog-adult-eat-0--black.webp'),
        require('../../../../assets/pets/dog-adult-eat-1--black.webp'),
        require('../../../../assets/pets/dog-adult-eat-2--black.webp'),
        require('../../../../assets/pets/dog-adult-eat-3--black.webp'),
      ],
      width: 255,
      height: 194,
      heightRatio: 0.8818,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/dog-adult-sleep-0--black.webp'),
        require('../../../../assets/pets/dog-adult-sleep-1--black.webp'),
        require('../../../../assets/pets/dog-adult-sleep-2--black.webp'),
        require('../../../../assets/pets/dog-adult-sleep-3--black.webp'),
      ],
      width: 200,
      height: 130,
      heightRatio: 0.5909,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/dog-adult-ball-0--black.webp'),
        require('../../../../assets/pets/dog-adult-ball-1--black.webp'),
        require('../../../../assets/pets/dog-adult-ball-2--black.webp'),
        require('../../../../assets/pets/dog-adult-ball-3--black.webp'),
      ],
      width: 203,
      height: 183,
      heightRatio: 0.8318,
    },
    house: {
      frames: [
        require('../../../../assets/pets/dog-adult-house-0--black.webp'),
        require('../../../../assets/pets/dog-adult-house-1--black.webp'),
        require('../../../../assets/pets/dog-adult-house-2--black.webp'),
        require('../../../../assets/pets/dog-adult-house-3--black.webp'),
      ],
      width: 213,
      height: 169,
      heightRatio: 0.7682,
    },
  },
  'dog-adult--brown': {
    idle: {
      frames: [
        require('../../../../assets/pets/dog-adult-idle-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-idle-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-idle-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-idle-3--brown.webp'),
      ],
      width: 207,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/dog-adult-walk-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-walk-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-walk-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-walk-3--brown.webp'),
      ],
      width: 206,
      height: 176,
      heightRatio: 0.8,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/dog-adult-dirty-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-dirty-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-dirty-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-dirty-3--brown.webp'),
      ],
      width: 205,
      height: 190,
      heightRatio: 0.8636,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/dog-adult-bath-0--brown.png'),
        require('../../../../assets/pets/dog-adult-bath-1--brown.png'),
        require('../../../../assets/pets/dog-adult-bath-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-bath-3--brown.png'),
        require('../../../../assets/pets/dog-adult-bath-4--brown.webp'),
        require('../../../../assets/pets/dog-adult-bath-5--brown.png'),
      ],
      width: 130,
      height: 154,
      heightRatio: 0.7,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/dog-adult-happy-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-happy-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-happy-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-happy-3--brown.webp'),
      ],
      width: 186,
      height: 214,
      heightRatio: 0.9727,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/dog-adult-eat-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-eat-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-eat-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-eat-3--brown.webp'),
      ],
      width: 255,
      height: 194,
      heightRatio: 0.8818,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/dog-adult-sleep-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-sleep-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-sleep-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-sleep-3--brown.webp'),
      ],
      width: 200,
      height: 130,
      heightRatio: 0.5909,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/dog-adult-ball-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-ball-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-ball-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-ball-3--brown.webp'),
      ],
      width: 203,
      height: 183,
      heightRatio: 0.8318,
    },
    house: {
      frames: [
        require('../../../../assets/pets/dog-adult-house-0--brown.webp'),
        require('../../../../assets/pets/dog-adult-house-1--brown.webp'),
        require('../../../../assets/pets/dog-adult-house-2--brown.webp'),
        require('../../../../assets/pets/dog-adult-house-3--brown.webp'),
      ],
      width: 213,
      height: 169,
      heightRatio: 0.7682,
    },
  },
  'pig-adult--black': {
    idle: {
      frames: [
        require('../../../../assets/pets/pig-adult-idle-0--black.webp'),
        require('../../../../assets/pets/pig-adult-idle-1--black.webp'),
        require('../../../../assets/pets/pig-adult-idle-2--black.webp'),
        require('../../../../assets/pets/pig-adult-idle-3--black.webp'),
      ],
      width: 242,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/pig-adult-walk-0--black.webp'),
        require('../../../../assets/pets/pig-adult-walk-1--black.webp'),
        require('../../../../assets/pets/pig-adult-walk-2--black.webp'),
        require('../../../../assets/pets/pig-adult-walk-3--black.webp'),
      ],
      width: 241,
      height: 198,
      heightRatio: 0.9,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/pig-adult-dirty-0--black.webp'),
        require('../../../../assets/pets/pig-adult-dirty-1--black.webp'),
        require('../../../../assets/pets/pig-adult-dirty-2--black.webp'),
        require('../../../../assets/pets/pig-adult-dirty-3--black.webp'),
      ],
      width: 243,
      height: 203,
      heightRatio: 0.9227,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/pig-adult-bath-0--black.png'),
        require('../../../../assets/pets/pig-adult-bath-1--black.png'),
        require('../../../../assets/pets/pig-adult-bath-2--black.webp'),
        require('../../../../assets/pets/pig-adult-bath-3--black.png'),
        require('../../../../assets/pets/pig-adult-bath-4--black.png'),
        require('../../../../assets/pets/pig-adult-bath-5--black.png'),
      ],
      width: 147,
      height: 155,
      heightRatio: 0.7045,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/pig-adult-happy-0--black.webp'),
        require('../../../../assets/pets/pig-adult-happy-1--black.webp'),
        require('../../../../assets/pets/pig-adult-happy-2--black.webp'),
        require('../../../../assets/pets/pig-adult-happy-3--black.webp'),
      ],
      width: 214,
      height: 232,
      heightRatio: 1.0545,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/pig-adult-eat-0--black.webp'),
        require('../../../../assets/pets/pig-adult-eat-1--black.webp'),
        require('../../../../assets/pets/pig-adult-eat-2--black.webp'),
        require('../../../../assets/pets/pig-adult-eat-3--black.webp'),
      ],
      width: 240,
      height: 196,
      heightRatio: 0.8909,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/pig-adult-sleep-0--black.webp'),
        require('../../../../assets/pets/pig-adult-sleep-1--black.webp'),
        require('../../../../assets/pets/pig-adult-sleep-2--black.webp'),
        require('../../../../assets/pets/pig-adult-sleep-3--black.webp'),
      ],
      width: 203,
      height: 143,
      heightRatio: 0.65,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/pig-adult-ball-0--black.png'),
        require('../../../../assets/pets/pig-adult-ball-1--black.png'),
        require('../../../../assets/pets/pig-adult-ball-2--black.webp'),
        require('../../../../assets/pets/pig-adult-ball-3--black.png'),
      ],
      width: 173,
      height: 136,
      heightRatio: 0.6182,
    },
    house: {
      frames: [
        require('../../../../assets/pets/pig-adult-house-0--black.webp'),
        require('../../../../assets/pets/pig-adult-house-1--black.webp'),
        require('../../../../assets/pets/pig-adult-house-2--black.webp'),
        require('../../../../assets/pets/pig-adult-house-3--black.webp'),
      ],
      width: 227,
      height: 172,
      heightRatio: 0.7818,
    },
  },
  'pig-adult--brown': {
    idle: {
      frames: [
        require('../../../../assets/pets/pig-adult-idle-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-idle-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-idle-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-idle-3--brown.webp'),
      ],
      width: 242,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/pig-adult-walk-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-walk-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-walk-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-walk-3--brown.webp'),
      ],
      width: 241,
      height: 198,
      heightRatio: 0.9,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/pig-adult-dirty-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-dirty-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-dirty-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-dirty-3--brown.webp'),
      ],
      width: 243,
      height: 203,
      heightRatio: 0.9227,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/pig-adult-bath-0--brown.png'),
        require('../../../../assets/pets/pig-adult-bath-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-bath-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-bath-3--brown.png'),
        require('../../../../assets/pets/pig-adult-bath-4--brown.png'),
        require('../../../../assets/pets/pig-adult-bath-5--brown.png'),
      ],
      width: 147,
      height: 155,
      heightRatio: 0.7045,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/pig-adult-happy-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-happy-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-happy-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-happy-3--brown.webp'),
      ],
      width: 214,
      height: 232,
      heightRatio: 1.0545,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/pig-adult-eat-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-eat-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-eat-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-eat-3--brown.webp'),
      ],
      width: 240,
      height: 196,
      heightRatio: 0.8909,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/pig-adult-sleep-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-sleep-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-sleep-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-sleep-3--brown.webp'),
      ],
      width: 203,
      height: 143,
      heightRatio: 0.65,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/pig-adult-ball-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-ball-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-ball-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-ball-3--brown.webp'),
      ],
      width: 173,
      height: 136,
      heightRatio: 0.6182,
    },
    house: {
      frames: [
        require('../../../../assets/pets/pig-adult-house-0--brown.webp'),
        require('../../../../assets/pets/pig-adult-house-1--brown.webp'),
        require('../../../../assets/pets/pig-adult-house-2--brown.webp'),
        require('../../../../assets/pets/pig-adult-house-3--brown.webp'),
      ],
      width: 227,
      height: 172,
      heightRatio: 0.7818,
    },
  },
  'monkey-adult--black': {
    idle: {
      frames: [
        require('../../../../assets/pets/monkey-adult-idle-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-idle-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-idle-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-idle-3--black.webp'),
      ],
      width: 213,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/monkey-adult-walk-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-walk-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-walk-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-walk-3--black.webp'),
      ],
      width: 212,
      height: 213,
      heightRatio: 0.9682,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/monkey-adult-dirty-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-3--black.webp'),
      ],
      width: 212,
      height: 219,
      heightRatio: 0.9955,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/monkey-adult-bath-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-bath-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-bath-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-bath-3--black.webp'),
        require('../../../../assets/pets/monkey-adult-bath-4--black.webp'),
        require('../../../../assets/pets/monkey-adult-bath-5--black.png'),
      ],
      width: 143,
      height: 164,
      heightRatio: 0.7455,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/monkey-adult-happy-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-happy-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-happy-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-happy-3--black.webp'),
      ],
      width: 191,
      height: 231,
      heightRatio: 1.05,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/monkey-adult-eat-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-eat-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-eat-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-eat-3--black.webp'),
      ],
      width: 232,
      height: 219,
      heightRatio: 0.9955,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/monkey-adult-sleep-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-3--black.png'),
      ],
      width: 185,
      height: 146,
      heightRatio: 0.6636,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/monkey-adult-ball-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-ball-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-ball-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-ball-3--black.webp'),
      ],
      width: 176,
      height: 193,
      heightRatio: 0.8773,
    },
    house: {
      frames: [
        require('../../../../assets/pets/monkey-adult-house-0--black.webp'),
        require('../../../../assets/pets/monkey-adult-house-1--black.webp'),
        require('../../../../assets/pets/monkey-adult-house-2--black.webp'),
        require('../../../../assets/pets/monkey-adult-house-3--black.webp'),
      ],
      width: 226,
      height: 170,
      heightRatio: 0.7727,
    },
  },
  'monkey-adult--brown': {
    idle: {
      frames: [
        require('../../../../assets/pets/monkey-adult-idle-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-idle-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-idle-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-idle-3--brown.webp'),
      ],
      width: 213,
      height: 220,
      heightRatio: 1.0,
    },
    walk: {
      frames: [
        require('../../../../assets/pets/monkey-adult-walk-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-walk-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-walk-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-walk-3--brown.webp'),
      ],
      width: 212,
      height: 213,
      heightRatio: 0.9682,
    },
    dirty: {
      frames: [
        require('../../../../assets/pets/monkey-adult-dirty-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-dirty-3--brown.webp'),
      ],
      width: 212,
      height: 219,
      heightRatio: 0.9955,
    },
    bath: {
      frames: [
        require('../../../../assets/pets/monkey-adult-bath-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-bath-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-bath-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-bath-3--brown.webp'),
        require('../../../../assets/pets/monkey-adult-bath-4--brown.webp'),
        require('../../../../assets/pets/monkey-adult-bath-5--brown.webp'),
      ],
      width: 143,
      height: 164,
      heightRatio: 0.7455,
    },
    happy: {
      frames: [
        require('../../../../assets/pets/monkey-adult-happy-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-happy-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-happy-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-happy-3--brown.webp'),
      ],
      width: 191,
      height: 231,
      heightRatio: 1.05,
    },
    eat: {
      frames: [
        require('../../../../assets/pets/monkey-adult-eat-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-eat-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-eat-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-eat-3--brown.webp'),
      ],
      width: 232,
      height: 219,
      heightRatio: 0.9955,
    },
    sleep: {
      frames: [
        require('../../../../assets/pets/monkey-adult-sleep-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-sleep-3--brown.webp'),
      ],
      width: 185,
      height: 146,
      heightRatio: 0.6636,
    },
    ball: {
      frames: [
        require('../../../../assets/pets/monkey-adult-ball-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-ball-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-ball-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-ball-3--brown.webp'),
      ],
      width: 176,
      height: 193,
      heightRatio: 0.8773,
    },
    house: {
      frames: [
        require('../../../../assets/pets/monkey-adult-house-0--brown.webp'),
        require('../../../../assets/pets/monkey-adult-house-1--brown.webp'),
        require('../../../../assets/pets/monkey-adult-house-2--brown.webp'),
        require('../../../../assets/pets/monkey-adult-house-3--brown.webp'),
      ],
      width: 226,
      height: 170,
      heightRatio: 0.7727,
    },
  },
};

/** Миска, вырезанная из кадра еды: та же, что в анимации. */
export const GENERATED_BOWLS: Record<
  string,
  { source: ImageSourcePropType; width: number; height: number }
> = {
  cat: {
    source: require('../../../../assets/pets/cat-bowl.png'),
    width: 64,
    height: 44,
  },
  dog: {
    source: require('../../../../assets/pets/dog-bowl.png'),
    width: 90,
    height: 53,
  },
  pig: {
    source: require('../../../../assets/pets/pig-bowl.png'),
    width: 76,
    height: 53,
  },
  monkey: {
    source: require('../../../../assets/pets/monkey-bowl.png'),
    width: 67,
    height: 41,
  },
};
