import type { PixelGrid } from '@/shared/ui/PixelSprite';

/**
 * Персонажи в полный рост для диалогов — 24×46.
 *
 * Показываются целиком сбоку от реплики и перекрывают комнату: ребёнок
 * видит, кто говорит, не читая имени.
 *
 * Силуэты различаются причёской, ростом и позой, а не только цветом
 * (требование art-style.md).
 *
 * Символы: x — обводка, h/H — волосы и тень, s/S — кожа и тень,
 * e — глаза, m — рот, c/C — одежда и тень, p/P — штаны и тень,
 * b — обувь, a — борода, '.' — прозрачно.
 */

type Actor = {
  rows: string[];
  palette: Record<string, string>;
};

const OUTLINE = '#2B1D14';

// Взрослый: рост во весь кадр, руки вдоль тела
const ADULT_SHORT_HAIR = [
  '........xxxxxxxx........',
  '.......xhhhhhhhhx.......',
  '......xhhhhhhhhhhx......',
  '.....xhhhhhhhhhhhhx.....',
  '.....xhhssssssssHhx.....',
  '.....xhssssssssssHx.....',
  '.....xsssssssssssSx.....',
  '.....xsEEsssssEEssx.....',
  '.....xsEeSsssSeEsSx.....',
  '.....xssssmmmssssSx.....',
  '.....xSssssssssssSx.....',
  '......xSsssssssSx.......',
  '.......xxsssssxx........',
  '.......xxcccccxx........',
  '....xxxcccccccccxxx.....',
  '...xccccccccccccccccx...',
  '..xcccccccccccccccccx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccCcccccCcccscx...',
  '..xscccCCcccccCCccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xxsccccccccccccsxx....',
  '...xxsccccccccccsxx.....',
  '....xxCCCCCCCCCCxx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xPPPPxxPPPPPx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xPPPPxxPPPPPx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xxxxxxxxxxxxx......',
  '....xbbbbxxxbbbbbx......',
  '....xbbbbxxxbbbbbx......',
  '....xxxxxxxxxxxxxx......',
  '........................',
];

// Взрослый с длинными волосами
const ADULT_LONG_HAIR = [
  '........xxxxxxxx........',
  '.......xhhhhhhhhx.......',
  '......xhhhhhhhhhhx......',
  '.....xhhhhhhhhhhhhx.....',
  '....xhhhssssssssHhhx....',
  '....xhhssssssssssHhx....',
  '....xhssssssssssssHx....',
  '....xhsEEsssssEEsshx....',
  '....xhsEeSsssSeEssHx....',
  '....xhsssssmmmsssshx....',
  '....xhSssssssssssShx....',
  '....xhhSsssssssShhx.....',
  '....xhhxxsssssxxhhx.....',
  '....xhhxcccccccxhhx.....',
  '....xxxcccccccccxxx.....',
  '...xccccccccccccccccx...',
  '..xcccccccccccccccccx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccCcccccCcccscx...',
  '..xscccCCcccccCCccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xxsccccccccccccsxx....',
  '...xxsccccccccccsxx.....',
  '....xxCCCCCCCCCCxx......',
  '.....xppppppppppppx.....',
  '.....xppppppppppppx.....',
  '.....xppppppppppppx.....',
  '.....xpppPPPPppppppx....',
  '.....xppppppppppppx.....',
  '.....xPPPPPPPPPPPPx.....',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xPPPPxxPPPPPx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xxxxxxxxxxxxx......',
  '....xbbbbxxxbbbbbx......',
  '....xbbbbxxxbbbbbx......',
  '....xxxxxxxxxxxxxx......',
  '........................',
];

// Взрослый с бородой
const ADULT_BEARD = [
  '........xxxxxxxx........',
  '.......xhhhhhhhhx.......',
  '......xhhhhhhhhhhx......',
  '.....xhhhhhhhhhhhhx.....',
  '.....xhhssssssssHhx.....',
  '.....xhssssssssssHx.....',
  '.....xsssssssssssSx.....',
  '.....xsEEsssssEEssx.....',
  '.....xsEeSsssSeEsSx.....',
  '.....xsaaaammmaaasx.....',
  '.....xSaaaaaaaaaaSx.....',
  '......xSaaaaaaaSx.......',
  '.......xxaaaaaxx........',
  '.......xxcccccxx........',
  '....xxxcccccccccxxx.....',
  '...xccccccccccccccccx...',
  '..xcccccccccccccccccx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccCcccccCcccscx...',
  '..xscccCCcccccCCccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xsccccccccccccccscx...',
  '..xxsccccccccccccsxx....',
  '...xxsccccccccccsxx.....',
  '....xxCCCCCCCCCCxx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xPPPPxxPPPPPx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xPPPPxxPPPPPx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xppppxxpppppx......',
  '.....xxxxxxxxxxxxx......',
  '....xbbbbxxxbbbbbx......',
  '....xbbbbxxxbbbbbx......',
  '....xxxxxxxxxxxxxx......',
  '........................',
];

// Ребёнок: крупная голова, ниже ростом, руки чуть в стороны
const CHILD = [
  '........................',
  '........................',
  '.......xxxxxxxxxx.......',
  '......xhhhhhhhhhhx......',
  '.....xhhhhhhhhhhhhx.....',
  '.....xhhhhhhhhhhhhx.....',
  '.....xhhssssssssHhx.....',
  '.....xhssssssssssHx.....',
  '.....xsssssssssssSx.....',
  '.....xsEEsssssEEssx.....',
  '.....xsEeSsssSeEsSx.....',
  '.....xsssssmmmsssSx.....',
  '.....xSssssssssssSx.....',
  '......xSsssssssSx.......',
  '.......xxsssssxx........',
  '.......xxcccccxx........',
  '...xxxxcccccccccxxxx....',
  '..xsxccccccccccccxsx....',
  '..xsxcccccccccccccxsx...',
  '..xsxccccCCCcccccxsx....',
  '..xsxcccCCCCCccccxsx....',
  '..xsxccccCCCcccccxsx....',
  '..xsxccccccccccccxsx....',
  '..xxxccccccccccccxxx....',
  '....xccccccccccccx......',
  '....xxCCCCCCCCCCxx......',
  '.....xppppxxppppx.......',
  '.....xppppxxppppx.......',
  '.....xppppxxppppx.......',
  '.....xppppxxppppx.......',
  '.....xPPPPxxPPPPx.......',
  '.....xppppxxppppx.......',
  '.....xppppxxppppx.......',
  '.....xppppxxppppx.......',
  '.....xxxxxxxxxxxx.......',
  '....xbbbbbxxbbbbbx......',
  '....xxxxxxxxxxxxxx......',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

const ACTORS: Record<string, Actor> = {
  mother: {
    rows: ADULT_LONG_HAIR,
    palette: {
      x: OUTLINE,
      h: '#A0522D',
      H: '#7A3D20',
      s: '#F2C6A0',
      S: '#D9A87F',
      e: OUTLINE,
      E: '#FFFFFF',
      m: '#B5503F',
      c: '#F2C63D',
      C: '#C79A22',
      p: '#8E6BD1',
      P: '#6748A6',
      b: '#3B2A1F',
      a: '#A0522D',
    },
  },
  father: {
    rows: ADULT_BEARD,
    palette: {
      x: OUTLINE,
      h: '#5A3A22',
      H: '#3E2716',
      s: '#EBB98F',
      S: '#CE9A70',
      e: OUTLINE,
      E: '#FFFFFF',
      m: '#B5503F',
      c: '#3FA9D8',
      C: '#2A7CA4',
      p: '#6E4B2A',
      P: '#4E341C',
      b: '#3B2A1F',
      a: '#5A3A22',
    },
  },
  teacher: {
    rows: ADULT_SHORT_HAIR,
    palette: {
      x: OUTLINE,
      h: '#6E6E6E',
      H: '#4D4D4D',
      s: '#F2C6A0',
      S: '#D9A87F',
      e: OUTLINE,
      E: '#FFFFFF',
      m: '#B5503F',
      c: '#8E6BD1',
      C: '#6748A6',
      p: '#3B2A1F',
      P: '#241A12',
      b: '#3B2A1F',
      a: '#6E6E6E',
    },
  },
  hero: {
    rows: CHILD,
    palette: {
      x: OUTLINE,
      h: '#C97D28',
      H: '#9A5C18',
      s: '#F7D2AE',
      S: '#DDB68F',
      e: OUTLINE,
      E: '#FFFFFF',
      m: '#B5503F',
      c: '#A98BE0',
      C: '#8E6BD1',
      p: '#3FA9D8',
      P: '#2A7CA4',
      b: '#3B2A1F',
      a: '#C97D28',
    },
  },
};

export function actorSprite(speaker: string): PixelGrid | null {
  const actor = ACTORS[speaker];
  return actor ? { rows: actor.rows, palette: actor.palette } : null;
}

export const ACTOR_WIDTH = 24;
export const ACTOR_HEIGHT = 46;
export const ACTOR_SPEAKERS = Object.keys(ACTORS);
